CREATE TABLE `tb_user` (
  `user_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID,不用于查询',
  `username` VARCHAR(16) NOT NULL COMMENT '用户名',
  `avatar_url` VARCHAR(255) NOT NULL DEFAULT 'https://weleness-1300955279.cos.ap-guangzhou.myqcloud.com/cdn/imgs/photo.jpg' COMMENT '用户头像地址',
  `password` VARCHAR(75) NOT NULL COMMENT '用户密码',
  `phone` VARCHAR(11) NOT NULL DEFAULT '0' COMMENT '不要求用户绑定手机号，0表示没有',
  `email` VARCHAR(33) NOT NULL COMMENT '用户邮箱',
  `gender` BIGINT(1) NOT NULL COMMENT '用户性别',
  `age` TINYINT(4) UNSIGNED NOT NULL DEFAULT '18' COMMENT '用户年龄',
  `area` VARCHAR(33) NOT NULL DEFAULT '无' COMMENT '用户所在地区，0表示用户没有填写',
  `profession` VARCHAR(33) NOT NULL DEFAULT '无' COMMENT '用户职业，0表示没有填写',
  `description` VARCHAR(33) NOT NULL DEFAULT '无' COMMENT '用户自定义描述，0表示没有填写',
  `article_count` MEDIUMINT(9) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户文章数量',
  `tag_count` MEDIUMINT(9) UNSIGNED NOT NULL  DEFAULT '0' COMMENT '用户标签数量',
  `follower_count` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户读者数量',
  `login_count` int(11)  UNSIGNED NOT NULL DEFAULT '1' COMMENT '用户登陆次数',
  `last_login` timestamp NOT NULL COMMENT '用户最后一次登陆的时间',
  `last_update` timestamp NOT NULL COMMENT '用户最后一次修改账号信息的时间',
  `create_time` timestamp NOT NULL COMMENT '账号创建时间',
  `locked` BIT(1) NOT NULL DEFAULT 0 COMMENT '账号是否被锁定',
  `message_count` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户收到的消息数',
  `oauth_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户第三方平台认证ID,0代表用户没有第三方平台认证',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `unique_key` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=2584419330884243457 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户表';